apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: radarr
          image: lscr.io/linuxserver/radarr:latest
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: Europe/Paris
          ports:
            - containerPort: 7878
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: storage
              mountPath: /config
              subPath: config/radarr
            - name: storage
              mountPath: /movies
              subPath: media/movies
            - name: storage
              mountPath: /downloads
              subPath: downloads
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: storage
